console.log(`Loaded: ${import.meta.url}`);

const _rawLang = {
    TRAITS: {
        STRENGTH: {"en": "PH",
            "pt-BR": "PH",},
        AGILITY: {"en": "PH",
            "pt-BR": "PH",},
        FINESSE: {"en": "PH",
            "pt-BR": "PH",},
        PRESENCE: {"en": "PH",
            "pt-BR": "PH",},
        INSTINCT: {"en": "PH",
            "pt-BR": "PH",},
        KNOWLEDGE: {"en": "PH",
            "pt-BR": "PH",},
    },
    ACTOR_TYPES: {
        ADVERSARY: {"en": "PH",
            "pt-BR": "PH",},
        ENVIRONMENT: {"en": "PH",
            "pt-BR": "PH",},
        PLAYER: {"en": "PH",
            "pt-BR": "PH",},
    },
    ITEM_TYPES: {
        ANCESTRY: {"en": "PH",
            "pt-BR": "PH",},
        ARMOR: {"en": "PH",
            "pt-BR": "PH",},
        CLASS: {"en": "PH",
            "pt-BR": "PH",},
        COMMON_ITEM: {"en": "PH",
            "pt-BR": "PH",},
        COMMUNITY: {"en": "PH",
            "pt-BR": "PH",},
        CONSUMABLE: {"en": "PH",
            "pt-BR": "PH",},
        DOMAIN: {"en": "PH",
            "pt-BR": "PH",},
        DOMAIN_CARD: {"en": "PH",
            "pt-BR": "PH",},
        FEATURE: {"en": "PH",
            "pt-BR": "PH",},
        MAGIC_ITEM: {"en": "PH",
            "pt-BR": "PH",},
        MATERIA: {"en": "PH",
            "pt-BR": "PH",},
        SPELL: {"en": "PH",
            "pt-BR": "PH",},
        SUBCLASS: {"en": "PH",
            "pt-BR": "PH",},
        WEAPON: {"en": "PH",
            "pt-BR": "PH",},
    },
    ADVERSARY_TYPES: {},
    ENVIRONMENT_TYPES: {},
    LEVEL_UP_OPTIONS: {
        HP: {"en": "PH",
            "pt-BR": "PH",},
        STRESS: {"en": "PH",
            "pt-BR": "PH",},
        EVASION: {"en": "PH",
            "pt-BR": "PH",},
        TRAIT: {"en": "PH",
            "pt-BR": "PH",},
        EXPERIENCE: {"en": "PH",
            "pt-BR": "PH",},
        DOMAIN_CARD: {"en": "PH",
            "pt-BR": "PH",},
        SUBCLASS: {"en": "PH",
            "pt-BR": "PH",},
        PROFICIENCY: {"en": "PH",
            "pt-BR": "PH",},
        MULTICLASS: {"en": "PH",
            "pt-BR": "PH",},
    }
}

export const _DO_NOT_USE_LANG = _rawLang;
