name: Validate and Build (CI)

on:
  push:
    branches: [stable]
  pull_request:
    branches: [stable]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install NodeJS (for less)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm ci

      - name: Run validation tools
        run: |
          python -m tools validate
